### ISSUE TITLE
Support json compare ignoring fields

### ISSUE THREAD

**Issue by madan-zeotap** [madan01/jsonxp#1]
support for JSON comparison ignoring field list. For example
{
	"country": {
		"234": {
			"name": "United Kingdom",
			"count": 70
		},
		"84": {
			"name": "Germany",
			"count": 121
		},
		"110": {
			"name": "Italy",
			"count": 231
		},
		"235": {
			"name": "US",
			"count": 501
		}
	}
}

**Comment by madan01** [comment]
fixed and added test
